version: '3.6'

services:
  db:
    image: postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: explorer
      POSTGRES_USER: minter
      POSTGRES_PASSWORD: password
    volumes:
      - ./tmp/postgresql:/var/lib/postgresql/data
  prometheus:
    image: prom/prometheus
    volumes:
      - ./tmp/prometheus:/etc/prometheus
      - ./tmp/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - 9090:9090
